name: Compile and commit Typst document
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.pdf'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  compile_typst_and_commit:
    name: Compile typst to pdf and commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Fonts
        uses: fontist/setup-fontist@v2
      - name: Install Fira Code
        run: |
          wget -O Fira_Sans.zip https://fonts.google.com/download?family=Fira%20Sans
          unzip -d fira_sans/ Fira_Sans.zip
          mv fira_sans /usr/share/fonts/
          fc-cache -fv
      - name: Install Noto Sans
        run: fontist install "Noto Sans"
      - name: Install Noto Sans CJK
        run: fontist install "Noto Sans CJK"
      - name: Install Noto Sans TC
        run: fontist install "Noto Sans TC"
      - name: setup typst
        uses: typst-community/setup-typst@v4
      - name: Compile Main
        run: typst compile main.typ main.pdf --font-path ~/.fontist/fonts
      - name: Compile Guide
        run: typst compile guide.typ guide.pdf --font-path ~/.fontist/fonts
      - name: Add and commit to main
        run: | 
          git config --global user.name 'Typst Compile Bot'
          git config --global user.email 'shubhssharma@proton.me'
          git add --force main.pdf guide.pdf
          git commit -m "[Bot] Update PDF"
          git push